{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latência por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_request_duration_seconds_sum[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exibir métricas específicas como latência por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_request_duration_seconds_sum[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contagem de Requisições por Status de Resposta (Duração em Segundos)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m])) by (code)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória por Instância e Job",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance, job) (process_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número total de threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (instance, job) (process_num_threads)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}