version: '3.4'

services:
  projetotech:
    image: ${DOCKER_REGISTRY-}projetotech
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      - postgres
    networks:
      - mynetwork
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080 

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    volumes:
      - /run/desktop/mnt/host/d/Git/Tech/src/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
