version: '3.4'

services:
  projetotech:
    image: ${DOCKER_REGISTRY-}projetotech
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Alterado para 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
