# Configuração global
global:
  scrape_interval: 15s # Intervalo de coleta definido para cada 15 segundos
  evaluation_interval: 15s # Avaliar regras a cada 15 segundos

# Configuração do Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # - alertmanager:9093

# Carregar regras uma vez e avaliá-las periodicamente de acordo com o 'evaluation_interval'
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Configuração de coleta
scrape_configs:
  # Coleta do próprio Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Coleta de Projetotech
  - job_name: "projetotech"
    static_configs:
      - targets: ["projetotech:8080"]
    metrics_path: "/metrics"
    scheme: "http"

  # Coleta de Cadastro Service
  - job_name: "cadastroservice"
    static_configs:
      - targets: ["cadastroservice:9000"]
    metrics_path: "/metrics"
    scheme: "http"

  # Coleta de Consulta Service
  - job_name: "consultaservice"
    static_configs:
      - targets: ["consultaservice:9010"]
    metrics_path: "/metrics"
    scheme: "http"

  # Coleta do API Gateway
  - job_name: "api-gateway"
    static_configs:
      - targets: ["OcelotApiGateway:5003"]
    metrics_path: "/metrics"
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
