apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    tier: backend
  annotations:
    app.kubernetes.io/created-by: "Ana e Daniel"
    app.kubernetes.io/description: "Gateway de entrada do sistema. Responsável por rotear as requisições para os microsserviços usando Ocelot."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: backend
      annotations:
        app.kubernetes.io/created-by: "Ana e Daniel"
        app.kubernetes.io/description: "Gateway de entrada do sistema. Responsável por rotear as requisições para os microsserviços usando Ocelot."
    spec:
      containers:
        - name: api-gateway
          image: biabachiega/api-gateway:latest
          ports:
            - containerPort: 5003
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://*:5003
