apiVersion: v1
kind: Service
metadata:
  name: cadastroservice
spec:
  type: NodePort
  selector:
    app: cadastroservice
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 31651
