apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastroservice
  annotations:
    app.kubernetes.io/description: "Serviço responsável pelo cadastro de contatos."
    app.kubernetes.io/author: "Ana e Daniel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastroservice
  template:
    metadata:
      labels:
        app: cadastroservice
    spec:
      containers:
        - name: cadastroservice
          image: biabachiega/cadastroservice:latest
          ports:
            - containerPort: 9000
          env:
            - name: ASPNETCORE_URLS
              value: http://*:9000
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: cadastroservice-config
                  key: RABBITMQ_HOST
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: cadastroservice-config
                  key: POSTGRES_HOST
