apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultaservice
  annotations:
    app.kubernetes.io/description: "Serviço responsável por consultar contatos."
    app.kubernetes.io/author: "Ana e Daniel"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consultaservice
  template:
    metadata:
      labels:
        app: consultaservice
    spec:
      containers:
        - name: consultaservice
          image: biabachiega/consultaservice:latest
          ports:
            - containerPort: 9010
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://*:9010
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: consultaservice-config
                  key: RABBITMQ_HOST
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: consultaservice-config
                  key: POSTGRES_HOST
