apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    app.kubernetes.io/author: Ana e Daniel
    app.kubernetes.io/description: Service interno para acesso ao banco PostgreSQL
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
