apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  annotations:
    app.kubernetes.io/author: Ana e Daniel
    app.kubernetes.io/description: Volume persistente para dados do PostgreSQL
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
