apiVersion: apps/v1
kind: Deployment
metadata:
  name: projetotech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projetotech
  template:
    metadata:
      labels:
        app: projetotech
    spec:
      containers:
        - name: projetotech
          image: biabachiega/projetotech:latest
          imagePullPolicy: IfNotPresent  # Usa a imagem do Minikube
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=1234
            - name: RABBITMQ_HOST
              value: rabbitmq

