apiVersion: apps/v1
kind: Deployment
metadata:
  name: projetotech
  labels:
    app: projetotech
    tier: backend
  annotations:
    author: "Ana e Daniel"
    description: "Microsserviço responsável pelas funcionalidades principais do sistema."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projetotech
  template:
    metadata:
      labels:
        app: projetotech
    spec:
      containers:
        - name: projetotech
          image: biabachiega/projetotech:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: projetotech-config
