apiVersion: v1
kind: Service
metadata:
  name: projetotech
spec:
  selector:
    app: projetotech
  ports:
    - protocol: TCP
      port: 8080       # Porta interna do cluster
      targetPort: 8080 # Porta no container
      nodePort: 31234  # Porta do host (Minikube) — opcional
  type: NodePort
