apiVersion: v1
kind: Service
metadata:
  name: workerservice
  annotations:
    author: "Ana e Daniel"
    description: "Service interno para o WorkerService"
spec:
  selector:
    app: workerservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
