apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerservice
  annotations:
    author: "Ana e Daniel"
    description: "Serviço worker responsável pela fila do rabbitmq."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workerservice
  template:
    metadata:
      labels:
        app: workerservice
    spec:
      containers:
        - name: workerservice
          image: biabachiega/workerservice:latest
          envFrom:
            - configMapRef:
                name: workerservice-config
