name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker image
      run: docker buildx build --tag projetotech:latest --file src/WebApplication1/Dockerfile src

    - name: Wait for PostgreSQL to be ready
      run: |
        sleep 30  # Adiciona uma pausa de 30 segundos para garantir que o PostgreSQL esteja pronto
        until docker-compose exec postgres pg_isready --host=postgres --username=postgres --dbname=postgres; do sleep 1; done

    - name: Run tests
      working-directory: src
      run: docker-compose run --rm projetotech dotnet test TestesFaseUm/TestesFaseUm.Tests.csproj
